EsParkApp Web Application/EsPark_WebApplication/Controllers/ParkingsController.cs
using EsPark_WebApplication.Helper.DTO;
using EsPark_WebApplication.Helper.DTO.ShowRequest;
using EsPark_WebApplication.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace EsPark_WebApplication.Controllers
{
    [Authorize]
    public class ParkingsController : Controller
    {
        private readonly EntitiesContext _ctx;


        public ParkingsController(EntitiesContext ctx)
        {
            _ctx = ctx;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult ShowParkings()
        {
            try
            {
                Request.Form.TryGetValue("draw", out Microsoft.Extensions.Primitives.StringValues drawOut);

                var draw = drawOut.FirstOrDefault();

                Request.Form.TryGetValue("start", out Microsoft.Extensions.Primitives.StringValues startOut);
                var start = startOut.FirstOrDefault();

                Request.Form.TryGetValue("length", out Microsoft.Extensions.Primitives.StringValues lengthOut);
                var length = lengthOut.FirstOrDefault();

                Request.Form.TryGetValue("order[0][column]", out Microsoft.Extensions.Primitives.StringValues orderColumnOut);
                Request.Form.TryGetValue("columns[" + orderColumnOut.FirstOrDefault() + "][name]", out Microsoft.Extensions.Primitives.StringValues columnsNameOut);
                var sortColumn = columnsNameOut.FirstOrDefault();

                Request.Form.TryGetValue("order[0][dir]", out Microsoft.Extensions.Primitives.StringValues sortColumnDirOut);
                var sortColumnDir = sortColumnDirOut.FirstOrDefault();

                Request.Form.TryGetValue("search[value]", out Microsoft.Extensions.Primitives.StringValues searchValueOut);
                var searchValue = searchValueOut.FirstOrDefault() ?? "";

                //Paging Size 
                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;
                var recordsTotal = _ctx.MP_PARKINGs.Where(t => t.JOB_OUT == null).Count();

                var ParkingListCount = _ctx.MP_PARKINGs.Where(w => w.LICENSEPLATE.Contains(searchValue) )
                    .Select(s => new showParkingsRequest()
                    {
                        DT_ParkingsId = "id_" + s.PARKINGID.ToString().Trim(),
                        parkingId = s.PARKINGID,
                        licenseplate = s.LICENSEPLATE,
                        startdate = s.STARTDATE.ToString("dd-MM-yyyy"),
                        parkingduration = s.PARKINGDURATION,
                        parkingfee = s.PARKINGFEE,
                        parkingdurationforovertime = s.PARKINGDURATIONFOROVERTIME,
                        parkingfeeforovertime = s.PARKINGFEEFOROVERTIME,
                        locId = (from y in _ctx.MP_LOCATIONs
                                    join z in _ctx.MP_JOBROTATIONHISTORYs on y.LOCID equals z.PARKID
                                    where z.ID == s.JOBROTATIONHISTORYID
                                    select y.LOCNAME).FirstOrDefault(),

                        deviceId = (from y in _ctx.MP_DEVICEs
                                   join z in _ctx.MP_JOBROTATIONHISTORYs on y.DEVICEID equals z.DEVICEID
                                   where z.ID == s.JOBROTATIONHISTORYID
                                   select y.SERIALNO).FirstOrDefault(),

                        rowId = (from y in _ctx.MP_USERs
                                     join z in _ctx.MP_JOBROTATIONHISTORYs on y.ROWID equals z.USERID
                                     where z.ID == s.JOBROTATIONHISTORYID
                                     select y.USERNAME).FirstOrDefault(),
                    }).Skip(skip).Take(pageSize).ToList();

                if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDir)))
                {
                    switch (sortColumn)
                    {
                        case "parkingId":
                            if (sortColumnDir == "desc")
                                ParkingListCount = (from o in ParkingListCount orderby o.parkingId descending select o).ToList();
                            else
                                ParkingListCount = (from o in ParkingListCount orderby o.parkingId ascending select o).ToList();
                            break;
                        case "licenseplate":
                            if (sortColumnDir == "desc")
                                ParkingListCount = (from o in ParkingListCount orderby o.licenseplate descending select o).ToList();
                            else
                                ParkingListCount = (from o in ParkingListCount orderby o.licenseplate ascending select o).ToList();
                            break;
                        case "startdate":
                            if (sortColumnDir == "desc")
                                ParkingListCount = (from o in ParkingListCount orderby o.startdate descending select o).ToList();
                            else
                                ParkingListCount = (from o in ParkingListCount orderby o.startdate ascending select o).ToList();
                            break;
                        case "rowId":
                            if (sortColumnDir == "desc")
                                ParkingListCount = (from o in ParkingListCount orderby o.rowId descending select o).ToList();
                            else
                                ParkingListCount = (from o in ParkingListCount orderby o.rowId ascending select o).ToList();
                            break;
                        case "locId":
                            if (sortColumnDir == "desc")
                                ParkingListCount = (from o in ParkingListCount orderby o.locId descending select o).ToList();
                            else
                                ParkingListCount = (from o in ParkingListCount orderby o.locId ascending select o).ToList();
                            break;

                        default:
                            if (sortColumnDir == "desc")
                                ParkingListCount = (from o in ParkingListCount orderby o.parkingId descending select o).ToList();
                            else
                                ParkingListCount = (from o in ParkingListCount orderby o.parkingId ascending select o).ToList();
                            break;
                    }
                }

                return Json(new
                {
                    draw = draw,
                    recordsFiltered = recordsTotal,
                    recordsTotal = recordsTotal,
                    data = ParkingListCount
                });
            }
            catch (Exception ex)
            {
                return Json(new { status = false, data = "", messages = ex.Message });
            }
        }

        [HttpPost]
        public async Task<IActionResult> ParkOut(int sId)
        {
            try
            {
                var current = await _ctx.MP_PARKINGs.Where(w => w.TARIFFID == sId).FirstOrDefaultAsync();
                if (current == null) return Json(new { status = false, data = "", Messages = "Ürün bulunamadı." });


               

                return Json(new { Status = true, Messages = "Online araç çıkış işlemi başarılı" });
            }
            catch (Exception ex)
            {
                return Json(new { Status = false, data = "", Messages = ex.Message });
            }
        }
        

    }
}

EsParkApp Web Application/EsPark_WebApplication/Views/Parkings/Index.cshtml
@{
    ViewData["Title"] = "Online Araç Çıkışı";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="px-5 py-5">
    <div class="px-5 py-5">
        <div class="px-5 py-5 col-12">
            <div class="card">
                <div class="card-header  ">
                    <h3 class="page-title pt-1 text-start">Online Araç Çıkışı</h3>
                </div>
            </div>
            <div class="card">
                <div class="table-responsive p-2">
                    <table id="aracCıkısı_table" class="table table-striped table-bordered dt-responsive nowrap" style="vertical-align:middle; width:100%;">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Plaka</th>
                                <th>Başlangıç</th>
                                <th>Tolerans</th>
                                <th>Peşin Odenen</th>
                                <th>Aşılan Süre (DK)</th>
                                <th>Ücret</th>
                                <th>Cihaz No</th>
                                <th>Lokasyon</th>
                                <th>Kullanıcı</th>
                                <th>İşlemler</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
            <div class="card-body">
            </div>
        </div>
    </div>
</div>

@section scripts {
    <script type="text/javascript">

        var parkingsTablo = null;

        $((_$) => {
            getParkingsAjax();
        });

        var getParkingsAjax = () => {
            if (parkingsTablo == null)
                parkingsTablo = $('#aracCıkısı_table').DataTable({
                    language: { url: '../dil.json' },
                    processing: true,
                    serverSide: true,
                    paging: true,
                    filter: true,
                    orderMulti: true,
                    order: [[1, "asc"]],
                    ajax: {
                        url: '@Url.Action("ShowParkings", "Parkings")',
                        type: "POST",
                        datatype: "json"
                    },
                    createdRow: function (row, data, dataIndex) {

                    },
                    columnDefs: [],
                    columns: [
                        {
                            "render": (data, type, row) => {
                                return row.parkingId;
                            }, "name": "parkingId"
                        },
                        {
                            "render": (data, type, row) => {
                                return row.licenseplate;
                            }, "name": "licenseplate"
                        },
                        {
                            "render": (data, type, row) => {
                                return row.startdate;
                            }, "name": "startdate"
                        },
                        {
                            "render": (data, type, row) => {
                                return row.parkingduration;
                            }, "name": "parkingduration"
                        },
                        { "render": (data, type, row) => { if (row.parkingfee == null) return row.parkingfee; else return '₺ ' + row.parkingfee;}, "name": "parkingfee" },
                        {
                            "render": (data, type, row) => {
                                return row.parkingdurationforovertime;
                            }, "name": "parkingdurationforovertime"
                        },
                        { "render": (data, type, row) => { if (row.parkingfeeforovertime == null) return row.parkingfeeforovertime; else return '₺ ' + row.parkingfeeforovertime;}, "name": "parkingfeeforovertime" },
                        {
                            "render": (data, type, row) => {
                                return row.deviceId;
                            }, "name": "deviceId"
                        },
                        {
                            "render": (data, type, row) => {
                                return row.locId;
                            }, "name": "locId"
                        },
                        {
                            "render": (data, type, row) => {
                                return row.rowId;
                            }, "name": "rowId"
                        },
                        {
                            "render": (data, type, row) => {
                                return `<button type="button" class="btn btn btn-outline-dark pt-2" onclick="javascript:parkOut(${row.parkingId})"><i class="dripicons-exit"></i></button>`;
                            }, "name": "rowId"
                        },



                    ],
                    fixedColumns: true,
                    scrollCollapse: true,
                    initComplete: function (settings, json) {
                        $('#aracCıkısı_table_filter input').unbind();
                        $('#aracCıkısı_table_filter input').bind('keyup', function (e) {
                            if (e.keyCode == 13) {
                                parkingsTablo.search(this.value).draw();
                            }
                        });

                        $('.dataTables_scrollBody').removeAttr('style').css({
                            'position': 'relative',
                            'overflow-y': 'auto',
                            'overflow-x': 'hidden',
                            'width': '100%',
                            'max-height': ((window.innerHeight / 2) + 120) + 'px'
                        });

                    }

                })
        }

        var parkOut = (selectId) => {

            var token = 'k7lFizdIpOicanrvRN3xSXbOOLABkMCN';

            var formData = new FormData();

            invoiceInfoObj = new Array();
            invoiceInfoObj =
                [
                    tutar = 6.00,
                    Plaka = "41 ya 585",
                    FisYazisi = "asd",
                    MuhKodu = "234",
                    KayitNo = 123,
                    JobId = 1,
                    PayType = 12234,
                    Ettn = "hvksjdhgjkvdfskgjdfkl",
                    NowTime = "21-01-2022"
                ];


            $.post('@Url.Action("CreateInvoice","DebitRecord")', { InvoiceInfo: invoiceInfoObj, token: token }, (d, s) => {

            })



            //Swal.fire({
            //    title:'Online araç çıkışı yapmak istediğinize emin misiniz?',
            //    icon:'question',
            //    showCancelButton: true,
            //    cancelButtonText: 'Hayır',
            //    confirmButtonColor: '#4a804d',
            //    cancelButtonColor: '#b22222',
            //    confirmButtonText: 'Evet',
            //})
            //    .then((result) => {
            //        if(result.value == true) {
            //            var postData = [{ "tutar": "1", "plaka": "41 ya 585", "FisYazisi": "12345", "MuhKodu": "999", "JobId": "5297", "PayType":"123" }
            //            ];

            //            $.getJSON('@Url.Action("ParkOut","Parkings")', {sId: selectId}, (d,s) => {
            //                if(s == "success"){
            //                    if(d.Status == true){
            //                        parkingsTablo.ajax.reload();
            //                        Swal.fire({ title: 'Online araç çıkışı gerçekleşti.', confirmButtonColor: '#1c6071', confirmButtonText: 'Tamam' })
            //                    } else {
            //                        Swal.fire({
            //                            icon: 'error',
            //                            title: 'Oops...',
            //                            text: 'Online araç çıkışı gerçekleşemedi.'
            //                        });
            //                    }
            //                }
            //                if (parkingsTablo != null)
            //                    parkingsTablo.ajax.reload();
            //            })
            //        }
            //    })
        }


    </script>
}