EsParkApp Web Application/EsPark_WebApplication/Controllers/ZReportController.cs
using EsPark_WebApplication.Helper.DTO;
using EsPark_WebApplication.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Numerics;

namespace EsPark_WebApplication.Controllers
{
    [Authorize]
    public class ZReportController : Controller
    {
        private readonly EntitiesContext _ctx;


        public ZReportController(EntitiesContext ctx)
        {
            _ctx = ctx;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult ShowOpenShifts()
        {
            try
            {
                Request.Form.TryGetValue("draw", out Microsoft.Extensions.Primitives.StringValues drawOut);

                var draw = drawOut.FirstOrDefault();

                Request.Form.TryGetValue("start", out Microsoft.Extensions.Primitives.StringValues startOut);
                var start = startOut.FirstOrDefault();

               

                Request.Form.TryGetValue("order[0][column]", out Microsoft.Extensions.Primitives.StringValues orderColumnOut);
                Request.Form.TryGetValue("columns[" + orderColumnOut.FirstOrDefault() + "][name]", out Microsoft.Extensions.Primitives.StringValues columnsNameOut);
                var sortColumn = columnsNameOut.FirstOrDefault();

                Request.Form.TryGetValue("order[0][dir]", out Microsoft.Extensions.Primitives.StringValues sortColumnDirOut);
                var sortColumnDir = sortColumnDirOut.FirstOrDefault();

                Request.Form.TryGetValue("search[value]", out Microsoft.Extensions.Primitives.StringValues searchValueOut);
                var searchValue = searchValueOut.FirstOrDefault() ?? "";

                //Paging Size 
                var recordsTotal = _ctx.MP_ZREPORTs.Where(t => t.REPORTTAKENDATE == null).Count();

                var OpenShiftListCount = _ctx.MP_ZREPORTs.Where(w => w.ID.ToString().Contains(searchValue) && w.REPORTTAKENDATE == null)
                    .Select(s => new showOpenShiftsRequest()
                    {
                        DT_ShiftId = "id_" + s.ID.ToString().Trim(),
                        ShiftId = s.ID,
                        Vardiya = s.CREATEDDATE.ToString("dd-MM-yyyy"),
                        
                        Lokasyon = _ctx.MP_LOCATIONs.Where(w => w.LOCID == _ctx.MP_JOBROTATIONHISTORYs.Where(t => t.ID == s.JOBROTATIONHISTORYID).Select(u => u.PARKID).FirstOrDefault()).Select(s => s.LOCNAME).FirstOrDefault(),
                        
                     
                        Kullanici = (from y in _ctx.MP_USERs
                                     join z in _ctx.MP_JOBROTATIONHISTORYs on y.ROWID equals z.USERID
                                     where z.ID == s.JOBROTATIONHISTORYID
                                     select y.USERNAME).FirstOrDefault(),
                    }).ToList();

                if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDir)))
                {
                    switch (sortColumn)
                    {
                        case "ShiftId":
                            if (sortColumnDir == "desc")
                                OpenShiftListCount = (from o in OpenShiftListCount orderby o.ShiftId descending select o).ToList();
                            else
                                OpenShiftListCount = (from o in OpenShiftListCount orderby o.ShiftId ascending select o).ToList();
                            break;
                        case "Vardiya":
                            if (sortColumnDir == "desc")
                                OpenShiftListCount = (from o in OpenShiftListCount orderby o.Vardiya descending select o).ToList();
                            else
                                OpenShiftListCount = (from o in OpenShiftListCount orderby o.Vardiya ascending select o).ToList();
                            break;
                        case "Lokasyon":
                            if (sortColumnDir == "desc")
                                OpenShiftListCount = (from o in OpenShiftListCount orderby o.Lokasyon descending select o).ToList();
                            else
                                OpenShiftListCount = (from o in OpenShiftListCount orderby o.Lokasyon ascending select o).ToList();
                            break;
                        case "Kullanici":
                            if (sortColumnDir == "desc")
                                OpenShiftListCount = (from o in OpenShiftListCount orderby o.Kullanici descending select o).ToList();
                            else
                                OpenShiftListCount = (from o in OpenShiftListCount orderby o.Kullanici ascending select o).ToList();
                            break;

                        default:
                            if (sortColumnDir == "desc")
                                OpenShiftListCount = (from o in OpenShiftListCount orderby o.ShiftId descending select o).ToList();
                            else
                                OpenShiftListCount = (from o in OpenShiftListCount orderby o.ShiftId ascending select o).ToList();
                            break;
                    }
                }

                return Json(new
                {
                    draw = draw,
                    recordsFiltered = recordsTotal,
                    recordsTotal = recordsTotal,
                    data = OpenShiftListCount
                });
            }
            catch (Exception ex)
            {
                return Json(new { status = false, data = "", messages = ex.Message });
            }
        }

        [HttpPost]
        public async Task<JsonResult> CheckShift(int[] pr)
        {
            try
            {

                var current = await _ctx.MP_ZREPORTs.Where(w => pr.Contains(w.ID)).ToListAsync();
                if (current == null) return Json(new { Status = false, data = "", Messages = "" });


                foreach (var debt in current)
                {
                debt.REPORTTAKENDATE = DateTime.Now;//Soft Delete
                }

                _ctx.MP_ZREPORTs.UpdateRange(current);

                await _ctx.SaveChangesAsync();

                return Json(new { Status = true, data = "", Messages = "" });

            }
            catch (Exception ex)
            {
                return Json(new { Status = false, data = "", messages = ex.Message });

            }
        }

    }
}

EsParkApp Web Application/EsPark_WebApplication/Views/ZReport/Index.cshtml
@{
    ViewData["Title"] = "Açık Kalan Vardiyalar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="px-5 py-5">
    <div class="px-5 py-5">
        <div class="px-5 py-5 col-12">
            <div class="card">
                <div class="card-header ">
                    <label class="col-7" style="font-size:24px;">Açık Kalan Vardiyalar</label>
                    <button type="button" class="btn btn btn-outline-warning col-2 " onclick="javascript:deleteCheck();" style="height:45px; font-size:15px;">Seçili Vardiyaları Kapat</button>
                    <button type="button" class="btn btn btn-outline-warning col-2 " onclick="javascript:deleteCheckAll();" style="height:45px; font-size:15px;">Tüm Vardiyaları Kapat</button>
                </div>
            </div>
            <div class="card">
                <div class="table-responsive p-2">
                    <table id="openShift_table" class="table table-striped table-bordered dt-responsive nowrap" style="vertical-align:middle; width:100%;">
                        <thead>
                            <tr>
                                <th></th>@*Checkbox*@
                                <th>Id</th>
                                <th>Vardiya Tarihi</th>
                                <th>Lokasyon</th>
                                <th>Kullanıcı Adı</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
            <div class="card-body">
            </div>
        </div>
    </div>
</div>

@section scripts {
    <script type="text/javascript">

        var openShiftsTablo = null;

        $((_$) => {
            getOpenShiftsAjax();
        });

        var getOpenShiftsAjax = () => {
            if (openShiftsTablo == null)
                openShiftsTablo = $('#openShift_table').DataTable({
                    language: { url: '../dil.json' },
                    processing: true,
                    serverSide: true,
                    paging: false,
                    filter: true,
                    orderMulti: true,
                    order: [[1, "asc"]],
                    ajax: {
                        url: '@Url.Action("ShowOpenShifts", "ZReport")',
                        type: "POST",
                        datatype: "json"
                    },
                    createdRow: function (row, data, dataIndex) {

                    },
                    columnDefs: [],
                    columns: [
                        {

                            "render": (data, type, row) => {

                                return `<div class="form-check form-check-inline"><input class="form-check-input debts" id="${row.ShiftId}" type="checkbox"></div>`;
                            }, "name": "Check"
                        },
                        {
                            "render": (data, type, row) => {
                                return row.ShiftId;
                            }, "name": "ShiftId"
                        },
                        {
                            "render": (data, type, row) => {
                                return row.Vardiya;
                            }, "name": "Vardiya"
                        },
                        {
                            "render": (data, type, row) => {
                                return row.Lokasyon;
                            }, "name": "Lokasyon"
                        },
                        {
                            "render": (data, type, row) => {
                                return row.Kullanici;
                            }, "name": "Kullanici"
                        },
                    ],
                    fixedColumns: true,
                    scrollCollapse: true,
                    initComplete: function (settings, json) {
                        $('#openShift_table_filter input').unbind();
                        $('#openShift_table_filter input').bind('keyup', function (e) {
                            if (e.keyCode == 13) {
                                openShiftsTablo.search(this.value).draw();
                            }
                        });

                        $('.dataTables_scrollBody').removeAttr('style').css({
                            'position': 'relative',
                            'overflow-y': 'auto',
                            'overflow-x': 'hidden',
                            'width': '100%',
                            'max-height': ((window.innerHeight / 2) + 120) + 'px'
                        });

                    }

                })
        }



        var deleteCheck = () => {
            if (document.querySelectorAll('.debts:checked').length == 0) {
                Swal.fire(
                    'Seçili Vardiya Bulunamadı.'
                )
                return;
            }

            let selectedDebts = document.querySelectorAll('.debts:checked');
            let parkingControlIDs = [];
            for (let debt of selectedDebts) {
                parkingControlIDs.push(debt.id.replace('checked_', ''));
                console.log(parkingControlIDs);
            }

            Swal.fire({
                title: 'Seçili vardiyaları kapatmak istediğinize emin misiniz?',
                icon: 'question',
                showCancelButton: true,
                cancelButtonText: 'Hayır',
                confirmButtonColor: '#4a804d',
                cancelButtonColor: '#b22222',
                confirmButtonText: 'Evet'
            })
                .then((result) => {

                    if (result.value == true) {
                        $.post('@Url.Action("CheckShift","ZReport")', { pr: parkingControlIDs }, (d, s) => {
                            if (s === "success") {

                                if (d.Status == true) {

                                    openShiftsTablo.ajax.reload();
                                    Swal.fire({ title: 'Vardiya kapatma işlemi gerçekleşti.', confirmButtonColor: '#1c6071', confirmButtonText: 'Tamam' });
                                }
                                else {
                                    Swal.fire({
                                        icon: 'error',
                                        title: 'Oops...',
                                        text: 'Vardiya kapatma işlemi gerçekleşemedi.'
                                    });
                                }

                            }
                            if (openShiftsTablo != null)
                                openShiftsTablo.ajax.reload();
                        });
                    }
                });
        }


        var deleteCheckAll = () => {

            if (openShiftsTablo == null) {
                Swal.fire({
                    icon: 'error',
                    text: 'Açık Vardiya Bulunmamaktadır.'
                });
            }

            let allDebts = $('.debts:checkbox');
            let parkingControlsId = [];
            for (let debt of allDebts) {
                parkingControlsId.push(debt.id.replace('checked_', ''));

            }

            Swal.fire({
                title: 'Tüm vardiyaları kapatmak istediğinize emin misiniz?',
                icon: 'question',
                showCancelButton: true,
                cancelButtonText: 'Hayır',
                confirmButtonColor: '#4a804d',
                cancelButtonColor: '#b22222',
                confirmButtonText: 'Evet'
            })
                .then((result) => {

                    if (result.value == true) {
                        $.post('@Url.Action("CheckShift","ZReport")', { pr: parkingControlsId }, (d, s) => {
                            if (s === "success") {

                                if (d.Status == true) {

                                    openShiftsTablo.ajax.reload();
                                    Swal.fire({ title: 'Vardiya kapatma işlemi gerçekleşti.', confirmButtonColor: '#1c6071', confirmButtonText: 'Tamam' });
                                }
                                else {
                                    Swal.fire({
                                        icon: 'error',
                                        text: 'Vardiya kapatma işlemi gerçekleşemedi.'
                                    });
                                }
                            }
                            if (openShiftsTablo != null)
                                openShiftsTablo.ajax.reload();
                        });
                    }
                });
        }

    </script>
}